### ISSUE TITLE
Help needed - empty report is generated

### ISSUE THREAD

**Issue by jzoran05** [red-gate/RedGate.Metrics#11]
Thank you for sharing the code with the community!
I am unable to get this script working on my git repo.
Would you be able to share "Invoke-FourKeyMetricsReportGeneration" invocation sample? I am guessing that some of my parameters are incorrect/wrong format but I am not sure which.

**Comment by garethbragg** [comment]
You're very welcome @jzoran05! Apologies for the slow reply.

Here's an example taken (almost) directly from one of our internal products:

```
$CheckoutLocation = Resolve-Path "C:\Checkouts\RepositoryRoot"
$ReportVersionNumber = Get-Date -UFormat "%y.%m.%d%H%M%S"

Invoke-FourKeyMetricsReportGeneration `
            -OctopusFeedApiKey $OctopusFeedApiKey `
            -CheckoutLocation $CheckoutLocation `
            -ProductName "Exciting Product" `
            -ReleaseTagPattern "releases/*.*" `
            -FixTagPattern "releases/*.**/fix" `
            -ReportPackageName "FourKeyMetrics-ExcitingProduct" `
            -ReportVersionNumber $ReportVersionNumber `
            -StartDate "01/01/2018" ` 
```

Does that help at all?

**Comment by zojovano** [comment]
Thanks! It is working now!

**Comment by garethbragg** [comment]
That's excellent news.

Can I ask what you had to change to get it working? 

Perhaps I'll be able to make it clearer for other people who try to pick this up.
