### ISSUE TITLE
Delivery Lead Time calculation logic question

### ISSUE THREAD

**Issue by sbrudz** [red-gate/RedGate.Metrics#7]
Thank you for open sourcing the code to generate these metrics.  It's very helpful to see a concrete implementation of how to gather and calculate these metrics.

In reading through the documentation, I was interested to see that you're using the average delivery lead time for each release to calculate the average Delivery Lead Time metric instead of averaging the delivery lead times of individual commits.  It seems like using an average of averages would be vulnerable to [Simpson's paradox](https://en.wikipedia.org/wiki/Simpson%27s_paradox), but maybe that's not a concern in this case.  Could you help me to understand the reasoning behind the calculation logic choice?

**Comment by garethbragg** [comment]
Thanks for taking an interest @sbrudz, I'm really glad you're finding it helpful.

From a quick look I believe you're right, the approach we've taken _does_ leave us vulnerable to Simpson's paradox.

This wasn't a conscious decision we took (I can't/don't claim to be a statistician). It's more an artefact of how we got to the implementation we have.

In our context, I'm not too worried about this hiding important signals. Anecdotally our Delivery Lead Time numbers and patterns match what we expect, and they certainly have shown some 'interesting' spikes when things have gone awry.

That said, it may be interesting to spike doing this with average lead times of individual commits, and see how different the output is!

**Comment by sbrudz** [comment]
Thank you for the fast response, @garethbragg.  That explanation makes sense.  It doesn't seem too concerning to me either.  The ranges listed for the levels of performance in the State of DevOps report differ roughly by order of magnitude, so any small errors probably won't have much of an impact.  If you end up doing the spike, though, I'd be interested in what you learn.

**Comment by Greg-Smulko** [comment]
Hi @sbrudz, I appreciate it's been over three years ;) , but it looks like @clivetong found this issue independently and proposed a fix in #19. That would be helpful if you'd be interested in confirming that the change matches your expectations. Cheers! :)

**Comment by sbrudz** [comment]
Hi @Greg-Smulko, the fix that @clivetong proposed addresses the issue I was concerned about.  I appreciate seeing the impact of the fix in the before and after graphs.  Thank you!

**Comment by garethbragg** [comment]
These changes are all in `main` now, so I think this can be closed.

Please do re-open if you disagree.

Thanks again for raising this @sbrudz.
